name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: applications/frontend/yarn.lock

      - name: Install dependencies 👨🏻‍💻
        run: yarn install --immutable
        working-directory: ./applications/frontend

      - name: Run linter 👀
        run: yarn lint --ignore-path ../../.gitignore
        working-directory: ./applications/frontend
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
