name: deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2

      - name: Install dependencies and build
        run: yarn install && yarn generate
        working-directory: ./applications/frontend
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: SSH key generate
        run: echo "$DEPLOY_KEY_SERVER" > key && chmod 600 key
        working-directory: ./applications/frontend
        env:
          DEPLOY_KEY_SERVER: ${{ secrets.DEPLOY_KEY_SERVER }}

      - name: Deploy
        run: rsync -auzrv -e "ssh -i key -p ${DEPLOY_PORT_SERVER} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" --delete ./dist/* ${DEPLOY_USER_SERVER}@${DEPLOY_HOST_SERVER}:${DEPLOY_HOST_PATH} --exclude .htaccess
        working-directory: ./applications/frontend
        env:
          DEPLOY_PORT_SERVER: ${{ secrets.DEPLOY_PORT_SERVER }}
          DEPLOY_USER_SERVER: ${{ secrets.DEPLOY_USER_SERVER }}
          DEPLOY_HOST_SERVER: ${{ secrets.DEPLOY_HOST_SERVER }}
          DEPLOY_HOST_PATH: ${{ secrets.DEPLOY_HOST_PATH }} 